export const bookApi=[
    {id:1,title:"c basic",desc:"C basics",rate:"4",author:"Dr.Jack",cost:"free",tag:"recommand",image:"https://m.media-amazon.com/images/I/41gMAhHiMpL.jpg"},
    {id:2,title:"data structure",desc:"lists",rate:"4.5",author:"Dr.GK.Leevy",cost:"$90",tag:"best",image:"https://m.media-amazon.com/images/I/51wUmAubIrL.jpg"},
    {id:3,title:"Data stucture linear list in c",rate:"4",desc:"C basics",cost:"$4",author:"Dr.Sam",tag:"recommand",image:"https://m.media-amazon.com/images/I/51cTUj438SL.jpg"},
    {id:4,title:"C Prograing",desc:"C basics",rate:"2",cost:"$6",author:"Dr.Chand",tag:"recommand",image:"https://m.media-amazon.com/images/I/51ve703aQ5L.jpg"},
    {id:5,title:"Basic Data",desc:"C basics",rate:"3",cost:"$89",author:"Dr.Aster",tag:"recommand",image:"https://kbimages1-a.akamaihd.net/b64e6509-ab28-46b0-b98d-6c026809f5ca/353/569/90/False/robbins-basic-pathology-e-book.jpg"},
    {id:6,title:"Data stucture linear list in c",rate:"5",desc:"C basics",cost:"$899",author:"Dr.Jerry",tag:"recommand",image:"https://accessiblepublishers.com/wp-content/uploads/2022/02/EP000132-1.jpg"},
    {id:7,title:"Data stucture linear list in c",rate:"2.5",desc:"C basics",cost:"$14",author:"Dr.Ravi",tag:"recommand",image:"https://i.pinimg.com/474x/06/31/bb/0631bb8da72119f587d668f6439bb3bf--free-ebooks-make-you-feel.jpg"},
    {id:9,title:"Data stucture linear list in c",rate:"4",desc:"C basics",cost:"$80",author:"Dr.Kumar",tag:"recommand",image:"https://www.madrasshoppe.com/135079-large_default/computer-applications-in-physics-with-fortran-basic-c-3-e-s-chandra.jpg"},
    {id:8,title:"Data stucture linear list in c",rate:"5",desc:"C basics",cost:"$64",author:"Dr.Leo",tag:"recommand",image:"https://i.pinimg.com/originals/86/f7/cb/86f7cb659f89e9137a395fae1f79ed3a.jpg"},
    {id:9,title:"Data stucture linear list in c",rate:"5",desc:"C basics",cost:"$80",author:"Dr.Kumar",tag:"recommand",image:"https://www.madrasshoppe.com/135079-large_default/computer-applications-in-physics-with-fortran-basic-c-3-e-s-chandra.jpg"},
    {id:10,title:"C Prograing",rate:"4",desc:"C basics",cost:"$86",author:"Dr.Mohit",tag:"best",image:"https://m.media-amazon.com/images/I/413gJ6yqSSL.jpg"},
    {id:11,title:"Basic Data",rate:"2",desc:"C basics",cost:"$90",author:"Dr.Suresh",tag:"best",image:"https://m.media-amazon.com/images/I/41+y+l0mlJL.jpg"},
    {id:12,title:"Data stucture linear list in c",rate:"5",desc:"C basics",cost:"$9",author:"Dr.Test",tag:"best",image:"https://m.media-amazon.com/images/I/41lXEvEdtKL._AC_SY780_.jpg"},
    {id:13,title:"Data stucture linear list in c",rate:"1.5",desc:"C basics",cost:"$44",author:"Dr.Mani",tag:"best",image:"https://m.media-amazon.com/images/I/61ECtTvHldL.jpg"},
    {id:14,title:"Data stucture linear list in c",rate:"5",desc:"C basics",cost:"free",author:"Dr.Richie",tag:"free",image:"https://m.media-amazon.com/images/I/41NWDiY0rML._SX376_BO1,204,203,200_.jpg"},
    {id:15,title:"Data stucture linear list in c",rate:"1",desc:"C basics",cost:"free",author:"Dr.Venkata",tag:"free",image:"https://m.media-amazon.com/images/I/516vd1AyVeL.jpg"},
    {id:16,title:"Data stucture linear list in c",rate:"3.5",desc:"C basics",cost:"free",author:"Dr.Richie",tag:"free",image:"https://images-na.ssl-images-amazon.com/images/I/41NFtdgGMtL._SX361_BO1,204,203,200_.jpg"},
    {id:17,title:"Data stucture linear list in c",rate:"2",desc:"C basics",cost:"free",author:"Dr.Chowdry",tag:"free",image:"https://www.falconpublishers.com/wp-content/uploads/2021/12/P-AP-EEE-2YR-3SEM-PC-C20-F.jpg"},
    {id:18,title:"Data stucture linear list in c",rate:"4",desc:"C basics",cost:"free",author:"Dr.Chowdry",tag:"free",image:"https://www.falconpublishers.com/wp-content/uploads/2021/06/P-AP-CME-1YR-1SEM-PRCF.jpg"},
]